### PR TITLE
Fix allocation when returning []byte to pool

### LINKED ISSUE #288: Buffer pool is causing an allocation on Put
The internal buffers package has a `Put` method with a signature of `Put([]byte)`

Casting a `[]byte` to an `interface{}` as we put the slice back in the underlying `sync.Pool` currently causes an allocation.

We should consider a wrapper type or using a `*[]byte` on `Put`

### PR DESCRIPTION
**Pull request by akshayjshah**
In order to pool byte slices without incurring an allocation (by casting into
`interface{}`), we need to switch to using a pointer type. The natural candidate
is the standard library's `bytes.Buffer`; it's a bit slower than straight
slices, but that's probably okay. However, we use `strconv.AppendFloat` and
friends to avoid allocations in the encoder, and those functions won't work with
`byte.Buffer`.

Instead, this PR adds a small `Buffer` type that implements just the bits of
`bytes.Buffer` and `strconv` that we need. It renames the private `buffers`
package to `bufferpool` to clarify the difference between the two.

Before:

```
BenchmarkZapWithoutFields-4      3000000               436 ns/op              80 B/op          2 allocs/op
```

After:

```
BenchmarkZapWithoutFields-4      5000000               331 ns/op              32 B/op          1 allocs/op
```

This fixes #288.

### CODE REVIEW

File: internal/bufferpool/bufferpool.go [hunk 1]
```diff
@@ -18,32 +18,30 @@
...
-// Package buffers provides strongly-typed functions to interact with a shared
-// pool of byte slices.
-//
-// It's used heavily inside zap, but callers may also take advantage of it;
-// it's particularly useful when implementing json.Marshaler, text.Marshaler,
-// and similar interfaces.
-package buffers
+// Package bufferpool provides strongly-typed functions to interact with a shared
+// pool of byte buffers.
+package bufferpool
```
Comment (akshayjshah) [inline internal/bufferpool/bufferpool.go]: The `Buffer` type needs to be non-internal, since it's part of the exported interfaces. The pool, however, should remain internal.

File: zapcore/console_encoder.go [hunk 2]
```diff
@@ -103,52 +102,52 @@ func (c consoleEncoder) EncodeEntry(ent Entry, fields []Field) ([]byte, error) {
 	// If there's no stacktrace key, honor that; this allows users to force
 	// single-line output.
 	if ent.Stack != "" && c.StacktraceKey != "" {
-		line.WriteByte('\n')
-		line.WriteString(ent.Stack)
+		line.AppendByte('\n')
```
Comment (akshayjshah) [inline zapcore/console_encoder.go]: Unfortunately, this triggers a variety of irritating `go vet` checks that attempt to enforce compliance with some interfaces in the standard lib.

File: buffer/buffer_test.go [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+	}{
+		{"AppendByte", func() { buf.AppendByte('v') }, "v"},
+		{"AppendString", func() { buf.AppendString("foo") }, "foo"},
+		{"AppendIntPositive", func() { buf.AppendInt(42) }, "42"},
+		{"AppendIntNegative", func() { buf.AppendInt(-42) }, "-42"},
+		{"AppendUint", func() { buf.AppendUint(42) }, "42"},
+		{"AppendBool", func() { buf.AppendBool(true) }, "true"},
+		{"AppendFloat64", func() { buf.AppendFloat(3.14, 64) }, "3.14"},
+		// Intenationally introduce some floating-point error.
+		{"AppendFloat32", func() { buf.AppendFloat(float64(float32(3.14)), 32) }, "3.14"},
```
Comment (akshayjshah) [inline buffer/buffer_test.go]: This tests that the `bitSize` parameter is being plumbed through correctly.

https://play.golang.org/p/ohu6TG6Ll6

File: buffer/buffer_test.go [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+		{"AppendWrite", func() { buf.Write([]byte("foo")) }, "foo"},
```
Comment (akshayjshah) [inline buffer/buffer_test.go]: :+1:

File: zapcore/console_encoder.go [hunk 5]
```diff
@@ -64,8 +63,8 @@ func (c consoleEncoder) Clone() Encoder {
 	return consoleEncoder{c.jsonEncoder.Clone().(*jsonEncoder)}
 }
 
-func (c consoleEncoder) EncodeEntry(ent Entry, fields []Field) ([]byte, error) {
-	line := bytes.NewBuffer(buffers.Get())
+func (c consoleEncoder) EncodeEntry(ent Entry, fields []Field) (*buffer.Buffer, error) {
```
Comment (akshayjshah) [inline zapcore/console_encoder.go]: Primary advantage is less concrete: it more cleanly separates encoders, which turn objects into bytes, and Facilities/WriteSyncers. It also preserves some degree of API similarity with the marshaler types in the standard library, which typically return `([]byte, error)`.

If you're staunchly against this, though, I can certainly switch.

File: buffer/buffer.go [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+}
+
+// AppendString writes a string to the Buffer.
+func (b *Buffer) AppendString(s string) {
+	b.bs = append(b.bs, s...)
+}
+
+// AppendInt appends an integer to the underlying buffer (assuming base 10).
+func (b *Buffer) AppendInt(i int64) {
+	b.bs = strconv.AppendInt(b.bs, int64(i), 10)
```
Comment (akshayjshah) [inline buffer/buffer.go]: :+1:

File: buffer/buffer_test.go (hunk 3 above)
Comment (prashantv) [inline buffer/buffer_test.go]: Ok cool, makes sense

File: zapcore/console_encoder.go (hunk 5 above)
Comment (prashantv) [inline zapcore/console_encoder.go]: I'm not very against it -- I do like the separation between encoders and writers, just wanted to make sure we were getting some other advantages for the cost of another public type.

File: zapcore/console_encoder.go (hunk 2 above)
Comment (prashantv) [inline zapcore/console_encoder.go]: That might not be so bad since then we'll implement `WriteString` with a return of `(int, error) which will allow `io.WriteString` to efficiently write a string to the buffer without converting to `[]byte`.

File: internal/bufferpool/bufferpool.go (hunk 1 above)
Comment (prashantv) [inline internal/bufferpool/bufferpool.go]: Ah fair enough.

File: zapcore/console_encoder.go (hunk 2 above)
Comment (akshayjshah) [inline zapcore/console_encoder.go]: It's actually the `WriteByte` method that gets flagged: https://golang.org/cmd/vet/#hdr-Methods

The returned error is particularly irritating because it then triggers `errcheck` if you don't use it.
