### PR TITLE
Open should only return close on success

### LINKED ISSUE #390: panic: runtime error: SIGSEGV on non existing directory
Hi,

There is panic (trying to execute nil function) when there is the directory non exists.

```
package main

import (
	"log"

	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

func main() {
	cfg := zap.NewProductionConfig()
	cfg.EncoderConfig.EncodeTime = zapcore.ISO8601TimeEncoder
	cfg.Level.SetLevel(zapcore.InfoLevel)
	cfg.DisableCaller = true
	cfg.OutputPaths = []string{"/tmp/non_existing_dir/file.log"}
	logger, err := cfg.Build() // panic()
	if err != nil {
		log.Fatal(err)
	}
	logger.Info("test message", zap.String("foo", "bar"))
}
```

After run: 

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x605933]

goroutine 1 [running]:
go.uber.org/zap.Config.openSinks(0xc420011218, 0x100, 0xc420011230, 0x699642, 0x4, 0x699426, 0x3, 0x6998f4, 0x5, 0x699318, ...)
	/usr/src/go/src/go.uber.org/zap/config.go:220 +0x193
go.uber.org/zap.Config.Build(0xc420011218, 0x100, 0xc420011230, 0x699642, 0x4, 0x699426, 0x3, 0x6998f4, 0x5, 0x699318, ...)
	/usr/src/go/src/go.uber.org/zap/config.go:161 +0xb1
main.main()
```

The problem is in `go.uber.org/zap/config.go#220 and 225-226` in openSinks method - there should be check for nil clouseOut/closeErr or zap.Open should return nopcloser function.

### PR DESCRIPTION
**Pull request by prashantv**
Config assumes that Open will always return a close function
which causes a panic when Open returns an error, since it doesn't
return a close function.

We can instead clean up the assumption that we return partial values
on error, and instead use a more common pattern:
 - On success, `err == nil` and all other return values are valid
 - On error, `err != nil` and all other return values are zero values

Fixes #390.

### CODE REVIEW

File: writer_test.go [hunk 1]
```diff
@@ -82,6 +85,26 @@ func TestOpen(t *testing.T) {
 	}
 }
 
+func TestOpenFails(t *testing.T) {
+	tests := []struct {
+		paths   []string
+		wantErr string
```
Comment (akshayjshah) [inline writer_test.go]: Since we're not using this, can we remove it?

Comment (prashantv) [inline writer_test.go]: 👍
