### PR TITLE
Fix handling of Time values out of UnixNano range

### LINKED ISSUE #737: inconsistent display of zap.Time field with zero time struct
When logging a zero initialized time.Time struct the output is not consistent:

```go
zap.L().With("time", time.Time{}).Debug("zero time")
```
Will output the time: `1754-08-30T22:43:41.128654848Z` because calling `UnixNano()` then `Unix(0, nsec)` is not symetric in this case.
The correct output would be `0001-01-01 00:00:00 +0000 UTC` (with the same layout as above).

see https://gist.github.com/patdowney/b64a4fee790ac66dd1a2 that exhibit the issue.

Looking at zap.Time I was wondering why you don't pass the Time struct in the Interface field instead of converting to an integer. Maybe this is to avoid making a new reference to traverse for the GC ?

https://github.com/uber-go/zap/blob/425214515ff452748375576b20c82524849177c6/field.go#L180-L184

https://github.com/uber-go/zap/blob/badef736563f8135e0add3232b06f58656da03c8/zapcore/field.go#L141-L147

### PR DESCRIPTION
**Pull request by prashantv**
Fixes #737, #803.

Time values are encoded by storing the UnixNano representation, but this
fails when the value of UnixNano is out of int64 range, see docs:

https://golang.org/pkg/time/#Time.UnixNano
> The result is undefined if the Unix time in nanoseconds cannot be
represented by an int64 (a date before the year 1678 or after 2262)

Fix this by storing values outside of UnixNano range as-is rather
than using UnixNano with a new Field type.

### CODE REVIEW

File: zapcore/field.go [hunk 1]
```diff
@@ -65,8 +65,11 @@ const (
 	Int8Type
 	// StringType indicates that the field carries a string.
 	StringType
-	// TimeType indicates that the field carries a time.Time.
+	// TimeType indicates that the field carries a time.Time that is
+	// representable by a UnixNano() stored as an int64.
 	TimeType
+	// TimeFullType indicates that the field carries a time.Time stored as-is.
+	TimeFullType
```
Comment (abhinav) [inline zapcore/field.go]: Are we sure introducing a new type is okay?
Would it make sense instead to store an invalid value like -1 in the integer field to indicate that the Interface field is set?

Comment (prashantv) [reply zapcore/field.go]: Since this is defined like an enum, I think it's reasonable to create new values here, but it will break anyone who introspects the internals of a field and only handles the known values.

I don't think we should use the integer field as:
 - The full value range can be used and is valid for existing values. Negative values just mean a time before the epoch. We'd need to truncate the range, but that would cause the following issue.
 - the current `Interface` is storing the timezone, while the new implementation stores a `time.Time` so code that assumes that a timezone is stored for `TimeType` will fail badly (likely panic)

Both options could break callers, but this approach is cleaner, and will only break those who did not assume that the `Type` enum may have new values -- which callers should expect. See similar change in the Go standard library that extends an enum to include a new value:
https://github.com/golang/go/commit/e64241216dd141589144a07f7f68acd64dc108fe

Comment (abhinav) [reply zapcore/field.go]: Makes sense.

File: field.go [hunk 2]
```diff
@@ -32,6 +32,11 @@ import (
 // improves the navigability of this package's API documentation.
 type Field = zapcore.Field
 
+var (
+	_minTimeInt64 = time.Unix(0, 0)
```
Comment (abhinav) [inline field.go]:
```suggestion
	_minTimeInt64 = time.Unix(0, math.MinInt64)
```

File: zapcore/field_test.go [hunk 3]
```diff
@@ -164,6 +165,10 @@ func TestFields(t *testing.T) {
 }
 
 func TestEquals(t *testing.T) {
+	timeOutOfRange := time.Unix(0, math.MaxInt64).Add(time.Nanosecond)
+	timeOutOfRangeNano := time.Unix(0, timeOutOfRange.UnixNano())
```
Comment (abhinav) [inline zapcore/field_test.go]: We should try out of range in both directions.

Comment (prashantv) [reply zapcore/field_test.go]: :+1: done

File: zapcore/field_test.go [hunk 4]
```diff
@@ -164,6 +165,14 @@ func TestFields(t *testing.T) {
 }
 
 func TestEquals(t *testing.T) {
+	// Values outside the UnixNano range were encoded incorrectly (#737, #803).
+	timeOutOfRangeHigh := time.Unix(0, math.MaxInt64).Add(time.Nanosecond)
+	timeOutOfRangeLow := time.Unix(0, math.MinInt64).Add(-time.Nanosecond)
+	timeOutOfRangeHighNano := time.Unix(0, timeOutOfRangeHigh.UnixNano())
+	timeOutOfRangeLowNano := time.Unix(0, timeOutOfRangeLow.UnixNano())
+	require.NotEqual(t, timeOutOfRangeHigh, timeOutOfRangeHighNano, "should be different as value is >  UnixNano range")
+	require.NotEqual(t, timeOutOfRangeHigh, timeOutOfRangeHighNano, "should be different as value is <  UnixNano range")
```
Comment (abhinav) [inline zapcore/field_test.go]: Should we use `Time.Equal` here? 
```suggestion
	require.False(t, timeOutOfRangeHigh.Equal(timeOutOfRangeHighNano), "should be different as value is >  UnixNano range")
	require.False(t, timeOutOfRangeHigh.Equal(timeOutOfRangeHighNano), "should be different as value is <  UnixNano range")
```
